apiVersion: v1
kind: Service
metadata:
  labels:
    service: broker-service
  name: broker-service
  namespace: kafka
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30005
  selector:
    service: broker-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: broker
  name: broker
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      hostname: broker
      containers:
      - env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: <ZOOKEEPER-INTERNAL-IP>:2181
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://broker:9092
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        name: broker
        ports:
        - containerPort: 9092