apiVersion: v1
kind: Service
metadata:
  labels:
    service: location-consumer
  name: location-consumer
spec:
  ports:
  - name: "5004"
    port: 5004
    targetPort: 5004
    nodePort: 30006
  selector:
    service: location-consumer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-consumer
  name: location-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-consumer
  template:
    metadata:
      labels:
        service: location-consumer
    spec:
      containers:
      - image: seaquenched/udaconnect-location-consumer
        name: location-consumer
        imagePullPolicy: Always
        env:
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              name: locations-cf
              key: KAFKA_URL
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: locations-cf
              key: KAFKA_TOPIC
      restartPolicy: Always